const latexCodes = [
    '\^\{', '\}', 
    '\_\{', '\}', 
    '\\sqrt\{', '\}', 
    '\\frac\{', '\}\{\}', 
    '\\sum\_\{', '\}\^\{\}', '\\prod\_\{', '\}\^\{\}', 
    '\\int\_\{', '\}\^\{\}', '\\sqrt\[\]\{', '\}', '\\oint\_\{', 
    '\}\^\{\}', '\\frac\{d ', '\}\{dx\}', '\\frac\{\\partial ', 
    '\}\{\\partial x\}', '\\implies ', '', '\\iff ', '', '\\times ', 
    '', '\\# ', '', '\\wedge ', '', '\\vee ', '', '\\in ', '', 
    '\\to ', '', '|', '', '\\lim_{x \\to 0} ', '', '\\infty ', '', 
    '\\pm ', '', '\\mp ', '', '\\emptyset ', '', '\\forall ', '', 
    '\\exists ', '', '\\neq ', '', '\\Delta ', '', '\\notin ', '', 
    '\\smallsetminus ', '', '\\nmid ', '', '\\{ ', ' \\}', '\\neg ', 
    '', '\\approx ', '', '\\lt ', '', '\\gt ', '', '\\le ', '', '\\ge ', '', 
    '\\leqslant ', '', '\\geqslant ', '', '\\ll ', '', '\\gg ', '', '\\prec ', 
    '', '\\succ ', '', '\\lesssim ', '', '\\gtrsim ', '', '\\nless ', '', 
    '\\ngtr ', '', '\\nleq ', '', '\\ngeq ', '', '\\nleqslant ', '', 
    '\\ngeqslant ', '', '\\nprec ', '', '\\nsucc ', '', '\\equiv ', '', 
    '\\sim ', '', '\\asymp ', '', '\\simeq ', '', '\\cong ', '', '\\nabla ', 
    '', '\\div ', '', '\\vdash ', '', '\\models ', '', '\\propto ', '', '\\Re ', 
    '', '\\Im ', '', '\\star ', '', '\\ast ', '', '\\circ ', '', '\\bullet ', '', 
    '\\imath ', '', '\\jmath ', '', '\\oplus ', '', '\\ominus ', '', '\\otimes ', '', 
    '\\oslash ', '', '\\cdot ', '', '\\hbar ', '', '\\cdots ', '', '\\vdots ', '', 
    '\\ddots ', '', '\\angle ', '', '\\bot ', '', '\\bowtie ', '', '\\parallel ', 
    '', '\\not\\equiv ', '', '\\nsim ', '', '\\ncong ', '', '\\nexists ', '', 
    '\\measuredangle ', '', '\\alpha', '', '\\beta', '', '\\gamma', '', '\\delta', 
    '', '\\epsilon', '', '\\varepsilon', '', '\\zeta', '', '\\eta', '', '\\theta', 
    '', '\\vartheta', '', '\\iota', '', '\\kappa', '', '\\lambda', '', '\\mu', '', 
    '\\nu', '', '\\xi', '', 'o', '', '\\pi', '', '\\varpi', '', '\\rho', '', 
    '\\varrho', '', '\\sigma', '', '\\varsigma', '', '\\tau', '', '\\upsilon', 
    '', '\\phi', '', '\\varphi', '', '\\chi', '', '\\psi', '', '\\omega', '', 
    '\\Gamma', '', '\\Delta', '', '\\Theta', '', '\\Lambda', '', '\\Xi', '', 
    '\\Pi', '', '\\Sigma', '', '\\Upsilon', '', '\\Phi', '', '\\Psi', '', 
    '\\Omega', '', '\\bigcup_\{', '\}\^\{\}', '\\bigcap_\{', '\}\^\{\}', 
    '\\bigvee_\{', '\}\^\{\}', '\\bigwedge_\{', '\}\^\{\}', '\\bigoplus_\{', '\}\^\{\}', 
    '\\bigotimes_\{', '\}\^\{\}', '\\coprod_\{', '\}\^\{\}', '\\bigsqcup_\{', '\}\^\{\}', 
    '\\subset ', '', '\\cup ', '', '\\cap ', '', '\\subseteq ', '', '\\subsetneq ', '', 
    '\\nsubseteq ', '', '\\bigtriangleup ', '', '\\bigtriangledown ', '', '\\bigcirc ', '', 
    '\\triangleleft ', '', '\\triangleright ', '', '\\square ', '', '\\gets ', '', 
    '\\to ', '', '\\longleftarrow ', '', '\\longrightarrow ', '', '\\leftrightarrow ', 
    '', '\\leftharpoonup ', '', '\\rightharpoonup ', '', '\\mapsto ', '', '\\longmapsto ', 
    '', '\\longleftrightarrow ', '', '\\leftharpoondown ', '', '\\rightharpoondown ', '', 
    '\\leftrightharpoons', '', '\\rightleftharpoons ', '', '\\updownarrow ', '', '\\uparrow ', 
    '', '\\downarrow ', '', '\\swarrow ', '', '\\searrow ', '', '\\upuparrows ', '', 
    '\\curvearrowleft ', '', '\\curvearrowright ', '', '\\nwarrow ', '', '\\nearrow ', '', 
    '\\rightrightarrows ', '', '\\circlearrowright ', '', '\\rightarrowtail ', '', 
    '\\rightsquigarrow ', '', '\\looparrowright ', '', '\\nrightarrow ', '', 
    '\\Leftarrow ', '', '\\Rightarrow ', '', '\\Leftrightarrow ', '', '\\Longleftarrow ', 
    '', '\\Longrightarrow ', '', '\\Longleftrightarrow ', '', '\\Uparrow ', '', 
    '\\Downarrow ', '', '\\Updownarrow ', '', '\\nLeftarrow ', '', 
    '\\nRightarrow ', '', '\\nLeftrightarrow ', '', '\\overrightarrow\{', '\}', 
    '\\underrightarrow\{', '\}', '\\widehat\{', '\}', '\\widetilde\{', '\}', 
    '\\overline\{', '\}', '\\underline\{', '\}', '\\overbrace\{', '\}', 
    '\\underbrace\{', '\}', '\\acute\{', '\}', '\\grave\{', '\}', '\\hat\{', '\}', 
    '\\tilde\{', '\}', '\\ddot\{', '\}', '\\bar\{', '\}', '\\mathbb\{', '\}', 
    '\\mathrm\{', '\}', '\\mathcal\{', '\}', '\\mathfrak\{', '\}', '\\mathscr\{', '\}', 
    '\\left\( ', ' \\right\)', '\\left\\lfloor ', ' \\right\\rfloor', '\\left\\{ ', 
    ' \\right\\}', '\\left\\lceil ', ' \\right\\rceil', '\\left\| ', ' \\right\|', 
    '\\left\[ ', ' \\right\]', '\\left\\| ', ' \\right\\|', '\\left\\langle ', 
    ' \\right\\rangle', '\\displaystyle ', '', '\\text\{', '\}', '\\textbf\{', '\}', 
    '\\mathrm\{C\}_\{', '\}\^\{\}', '\\binom\{', '\}\{\}', '\\overset\{\}\{', '\}', 
    '\\underset\{\}\{', '\}'];
